//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aparencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aparencia()
        {
            this.Personagems = new HashSet<Personagem>();
        }
    
        public int IdAparencia { get; set; }
        public decimal Peso { get; set; }
        public decimal Altura { get; set; }
        public string CorCabelo { get; set; }
        public string EstiloCabelo { get; set; }
        public string CorOlho { get; set; }
        public string CorPele { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Personagem> Personagems { get; set; }
    }
}
