//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personagem
    {
        public int Id { get; set; }
        public Nullable<int> HabilidadeId { get; set; }
        public Nullable<int> RacaId { get; set; }
        public Nullable<int> SubclasseId { get; set; }
        public Nullable<int> Nivel { get; set; }
        public string Nome { get; set; }
        public Nullable<System.DateTime> DataNasc { get; set; }
        public string Sexo { get; set; }
        public Nullable<int> Forca { get; set; }
        public Nullable<int> Destreza { get; set; }
        public Nullable<int> Sabedoria { get; set; }
        public Nullable<int> Constituicao { get; set; }
        public Nullable<int> Inteligencia { get; set; }
        public Nullable<int> Carisma { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public Nullable<decimal> Altura { get; set; }
        public Nullable<int> CorCabeloId { get; set; }
        public string EstiloCabelo { get; set; }
        public Nullable<int> CorOlhoId { get; set; }
        public Nullable<int> CorPeleId { get; set; }
    
        public virtual Cor Cor { get; set; }
        public virtual Cor Cor1 { get; set; }
        public virtual Cor Cor2 { get; set; }
        public virtual Habilidade Habilidade { get; set; }
        public virtual Raca Raca { get; set; }
        public virtual Subclasse Subclasse { get; set; }
    }
}
